### PR TITLE
PIMS-1985: Agency selection on add property

### PR DESCRIPTION
**Pull request by GrahamS-Quartech**
## 🎯 Summary

  
[PIMS-1985](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1985)

* Added a hook that lets you easily get the list of agencies only relevant to the current user. 
* Made the agency dropdown a part of the general info form so that it will be displayed both when adding or updating a project.
* The dropdown will show you the user's parent agency and children if you are a general user, or simply all agencies if you are an admin.

## 🔰 Checklist

- [x] I have read and agree with the following checklist and am following the guidelines in our [Code of Conduct](CODE_OF_CONDUCT.md) document.

> - I have performed a self-review of my code.
> - I have commented my code, particularly in hard-to-understand areas.
> - I have made corresponding changes to the documentation where required.
> - I have tested my changes to the best of my ability.
> - My changes generate no new warnings.

### CODE REVIEW

**Review by LawrenceLau2020 — COMMENTED** [review]
I made myself a General user with agency of "School District 100" whose parent is Educationa and Child Care (ECC). I seem to be only able to see my own agency and none of the other children agencies of ECC.

**Comment by dbarkowsky** [comment]
> I made myself a General user with agency of "School District 100" whose parent is Education and Child Care (ECC). I seem to be only able to see my own agency and none of the other children agencies of ECC.

This is what we want, right? Users of parent agencies can see the children, but child agencies cannot.

**Comment by GrahamS-Quartech** [comment]
> > I made myself a General user with agency of "School District 100" whose parent is Education and Child Care (ECC). I seem to be only able to see my own agency and none of the other children agencies of ECC.
> 
> This is what we want, right? Users of parent agencies can see the children, but child agencies cannot.

Yeah this is intentional from what I understood.

**Comment by LawrenceLau2020** [comment]
> > > I made myself a General user with agency of "School District 100" whose parent is Education and Child Care (ECC). I seem to be only able to see my own agency and none of the other children agencies of ECC.
> > 
> > 
> > This is what we want, right? Users of parent agencies can see the children, but child agencies cannot.
> 
> Yeah this is intentional from what I understood.

Ok, sounds good, I must have misunderstood the requirements.

**Review by dbarkowsky — APPROVED** [review]
This is working for me now as expected. 
Thanks for adding the indented select options.

**Review by LawrenceLau2020 — APPROVED** [review]
Works well, was able to see only my agency when my user's agency is a child agency, and tested as a user belonging to a parent agency, was able to change an existing property to other child agencies.

**Comment by GrahamS-Quartech** [comment]
> I made myself a General user with agency of "School District 100" whose parent is Education and Child Care (ECC). I seem to be only able to see my own agency and none of the other children agencies of ECC.

Just adding for documentation purposes that I checked in with Josh and Steven and this is indeed the expected behavior. So I will now merge.

**Pull request merged**
