### PR TITLE
Fixed "Add a Building" and "Create Disposal Project" Forms

### PR DESCRIPTION
**Pull request by ZachBourqueBCGov**
# Description

1. Add a Building
  a. Fixed numerous UI issues caused by upgrading bootstrap

2. Create Disposal Project
  a. Fixed the way that each step of the form is rendered, previously they were rendering using the Route component, which broke when updating dependencies.
  b. Fixed numerous UI Issues
  c. Removed links for "Other projects using this property" field, as the Routes have been removed. They can be added back at a later date

Fixes # (issue)
[PIMS-344](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-344)
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by BradyMitch** [comment]
Bootstrap for "Add a Building" seems to be fixed.

Still issues with "Create Disposal Project" bootstrap, here is page 2 of the form:

bootstrap-zach-pr

**Comment by LawrenceLau2020** [comment]
Getting some console errors on the ProjectDraftForm when clicking in the "Project Agency" typeahead text box:

image

**Comment by BradyMitch** [comment]
> Getting some console errors on the ProjectDraftForm when clicking in the "Project Agency" typeahead text box:
> 
> image

These are fixed in my pr that hasn't been merged yet.

**Comment by BradyMitch** [comment]
> > > Getting some console errors on the ProjectDraftForm when clicking in the "Project Agency" typeahead text box:
> > > image
> > 
> > 
> > These are fixed in my pr that hasn't been merged yet: #1299
> 
> I don't think @ZachBourqueBCGov has rebased this branch your latest changes yet, as I'm seeing that seticon error when clicking on a property from the View Inventory page. I did a merge into pims-63 this morning.

That was another PR that was merged this morning.

**Comment by ZachBourqueBCGov** [comment]
> > > These are fixed in my pr that hasn't been merged yet: #1299
> > 
> > 
> > I don't think @ZachBourqueBCGov has rebased this branch your latest changes yet, as I'm seeing that seticon error when clicking on a property from the View Inventory page. I did a merge into pims-63 this morning.
> 
> That was another PR that was merged this morning. Also: It has merge conflicts, I will resolve these soon.

This PR has since been rebased and the form layout issue has been fixed as well

**Pull request closed without merging**
