### PR TITLE
Updated dest email for pims support (PA-14).

### PR DESCRIPTION
**Pull request by Bruce451**
The email address is incorrect on the PIMS Ask For Help feature.  The email address should be:

citz_rpd_imit_help@gov.bc.ca

### CODE REVIEW

**Review by LawrenceLau2020 — APPROVED** [review]

**Comment by Bruce451** [comment]
Hi Jeremy,

Our most recent pull request appears to result in a codecov failed issue.  Not sure how to approach it.  Any ideas?

**Comment by Fosol** [comment]
Looks like something needs to be updated in the GitHub action and CodeCove.  The error states the following `{'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}`

Offhand I don't know the cause, I'd have to search and debug it.

**Comment by Fosol** [comment]
@Bruce451 I've submitted a PR to fix the codecov action.  Just approve it and merge it.  Then update this PR by rebasing it with the latest fix.

**Review by LawrenceLau2020 — APPROVED** [review]

**Review by Fosol — APPROVED** [review]
cheer

**Pull request merged**
