### PR TITLE
PIMS-327 - Update styled-components from version `6.0.7` to `6.1.0`

### PR DESCRIPTION
**Pull request by Sharala-Perumal**
PIMS-327: Update styled-components from version `6.0.7` to `6.1.0`

## 🎯 Summary

  
[PIMS-327](https://citz-imb.atlassian.net/browse/PIMS-327)

## 🔰 Checklist

- [x] I have read and agree with the following checklist and am following the guidelines in our [Code of Conduct](CODE_OF_CONDUCT.md) document.

> - I have performed a self-review of my code.
> - I have commented my code, particularly in hard-to-understand areas.
> - I have made corresponding changes to the documentation where required.
> - I have tested my changes to the best of my ability.
> - My changes generate no new warnings.

### CODE REVIEW

**Comment by TaylorFries** [comment]
When testing this branch I have hit the following error: 
`ERROR in src/features/projects/dispose/steps/SelectProjectPropertiesStep.tsx:95:15
TS2590: Expression produces a union type that is too complex to represent.
     93 |             <p style={{ float: 'right' }}>
     94 |               Show{' '}
  >  95 |               <LinkButton
        |               ^^^^^^^^^^^
  >  96 |                 onClick={handleShowSurplusClick}
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  >  97 |                 variant="link"
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  >  98 |                 style={checkSelected('Surplus Only') && { color: '#1a5a96' }}
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  >  99 |               >
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  > 100 |                 Surplus Active
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  > 101 |               </LinkButton>{' '}
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    102 |               |{' '}
    103 |               <LinkButton
    104 |                 style={checkSelected('All') && { color: '#1a5a96' }}`

**Comment by dbarkowsky** [comment]
> When testing this branch I have hit the following error:

Same issues I had. Fixing that one issue just identifies the next component using `styled-components`. 
Might be a reason to convert all of these components to .scss classes.

**Review by LawrenceLau2020 — COMMENTED** [review]
I'm also getting the same issue:

image

**Comment by Sharala-Perumal** [comment]
Because of the issues(mentioned above) we are encountering with this version, this PR will be closed. This ticket will be revisited with the release of the next version.

**Pull request closed without merging**
