### PR TITLE
Fix Sonarqube log4j security issue

### PR DESCRIPTION
**Pull request by Fosol**
I've update the image, but the deployment appears to be really slow.  Not sure if it's working atm.

### CODE REVIEW

**Review by LawrenceLau2020 — APPROVED** [review]

**Comment by LawrenceLau2020** [comment]
Hi Jeremy, should we also update the owasp-zap plugin to v2.11.1 for Jenkins in this PR as well?
https://www.zaproxy.org/blog/2021-12-10-zap-and-log4shell/

**Comment by Fosol** [comment]
I don't see it in our image registry.

**Comment by LawrenceLau2020** [comment]
> I don't see it in our image registry.

Is it not just changing the version number using an install command using python? I see this in the "Dockerfile" in jenkins-slave-zap folder:

`pip install python-owasp-zap-v2.4`

**Comment by Fosol** [comment]
Ah yes I suppose that might do it.  I suspect this isn't accessible externally though.

**Comment by LawrenceLau2020** [comment]
> Ah yes I suppose that might do it. I suspect this isn't accessible externally though.

It's actually on the github repo: https://github.com/zaproxy/zaproxy/releases/tag/v2.11.1

**Pull request merged**
