### PR TITLE
PIMS-1771: Parcel building union view 

### PR DESCRIPTION
**Pull request by GrahamS-Quartech**
## 🎯 Summary

  
[PIMS-1771](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1771)

Just adding a new view so that we can more easily display the parcels and buildings in the same table on the front end. Mostly to facilitate the server side pagination ticket, since it's not really possible to sort and paginate effectively unless we are performing that action on a single table (view).

## 🔰 Checklist

- [x] I have read and agree with the following checklist and am following the guidelines in our [Code of Conduct](CODE_OF_CONDUCT.md) document.

> - I have performed a self-review of my code.
> - I have commented my code, particularly in hard-to-understand areas.
> - I have made corresponding changes to the documentation where required.
> - I have tested my changes to the best of my ability.
> - My changes generate no new warnings.

### CODE REVIEW

**Comment by GrahamS-Quartech** [comment]
> Should we add lot size to this for Parcels? It's used in the inventory table.

True, didn't notice this before, I will add it. Also, I welcome suggestions for better naming for this view/entity, couldn't think of anything more appropriate.

**Comment by LawrenceLau2020** [comment]
> > Should we add lot size to this for Parcels? It's used in the inventory table.
> 
> True, didn't notice this before, I will add it. Also, I welcome suggestions for better naming for this view/entity, couldn't think of anything more appropriate.

Could this be called a property_list view?

**Comment by GrahamS-Quartech** [comment]
> Could this be called a property_list view?

I think it sounds too "plural". Other tables are named as a singular. PropertyUnion feels like it has this problem a bit too but it's a bit more ambiguous at least.

**Review by dbarkowsky — APPROVED** [review]
Works well for me. Not picky about the name. PropertyUnion describes it well enough.

**Pull request merged**
