### PR TITLE
Bumped react-router-dom from 6.2.1 to 6.3.0

### PR DESCRIPTION
**Pull request by ZachBourqueBCGov**
# Description

Updated react-router-dom from version 6.2.1 to 6.3.0

Fixes [#266](https://apps.itsm.gov.bc.ca/jira/secure/RapidBoard.jspa?rapidView=294&projectKey=PIMS&view=detail&selectedIssue=PIMS-266)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Fosol — APPROVED** [review]
When you `npm install` did you have to `npm install --force`?  What version of node and npm are you running?

**Comment by ZachBourqueBCGov** [comment]
> When you `npm install` did you have to `npm install --force`? What version of node and npm are you running?

No I didn't have to use --force.

I have been testing the app by running the containers as to have my computer's setup interfere as little as possible. 
That being said, installed on my local I have Node 16.17.0 and npm 8.5.5

**Comment by LawrenceLau2020** [comment]
> @LawrenceLau2020 are you also using node `16.17.0`? If so we should update the devcontainer so that it uses that too. This may solve issues with the PR I put together which required me to update the packages.

I'm using 14.19.3 actually for node locally, and npm is 8.5.5.

**Comment by Fosol** [comment]
We can't have different versions of node locally and with the final image.  I'll let you figure out what version works.  If the newer one works we need to upgrade the Openshift images and the devcontainer.

**Review by LawrenceLau2020 — APPROVED** [review]

**Pull request merged**
