### PR TITLE
PIMS-425: CHES api url changes 

### PR DESCRIPTION
**Pull request by LawrenceLau2020**
# Description
[//]: # (THESE COMMENTS ARE HIDDEN WHEN THE PR IS PUBLISHED, no need to remove them.)
[//]: # (Please include a summary of the changes.)
This ticket is to address the changes to the host and auth urls for the CHES api which need to be done before Dec.31, 2022.

An access request was submitted for the new credentials to the new CHES api in "dev" as well as "test". I will submit the request for access to the new CHES API in production once we've at least migrated to DEV.

When this PR gets merged to DEV, we will need to update the CHES_PASSWORD and CHES_USERNAME secrets in OpenShift and then the same when it gets migrated to TEST and Production.

For testing locally, you'll need to update your /backend/api/.env file with the new Ches__Username and CHES__Password credentials that I will email to you.

It seems to be working on my local machine, but it would be good if someone else could also test this.

[](https://hamzamohdzubair.github.io/redant/)

[//]: # (THESE COMMENTS ARE HIDDEN WHEN THE PR IS PUBLISHED, no need to remove them.)
[//]: # (Please include a list of Jira tickets and or Issues this PR resolves.)

[PIMS-425](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-425) CHES api url changes .

[](https://hamzamohdzubair.github.io/redant/)

[//]: # (THESE COMMENTS ARE HIDDEN WHEN THE PR IS PUBLISHED, no need to remove them.)
[//]: # (Please include a list of known issues if there are any.)

- None listed.

## Type of change
[//]: # (THESE COMMENTS ARE HIDDEN WHEN THE PR IS PUBLISHED, no need to remove them.)
[//]: # (Please delete options that are not relevant.)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Dependency updates (may include refactoring of a dependencies functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
[//]: # (THESE COMMENTS ARE HIDDEN WHEN THE PR IS PUBLISHED, no need to remove them.)
[//]: # (Please describe the tests that you ran to verify your changes.)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by BradyMitch** [comment]
Can you add something to the [Wiki](https://github.com/bcgov/PIMS/wiki/Development) so new team members know how to request and put these new credentials into their `.env`

**Comment by BradyMitch** [comment]
Im getting the following error when clicking Submit at the end of the Create Disposal Project form:

```
/api/projects/dispos: Bad Request data: {"error":"HTTP Request 'https://dev.oidc.gov.bc.ca/auth/realms/jbd6rnxw/protocol/openid-connect/token' failed\n","type":"ChesException","details":"\n\n\n","stackTrace":" at Pims.Ches.ChesService.GetTokenAsync(String username, String password) in /src/ches/ChesService.cs:line 199\n at Pims.Ches.ChesService.RefreshAccessTokenAsync() in /src/ches/ChesService.cs:line 79\n at Pims.Ches.ChesService.SendAsync[TR,TD](String endpoint, HttpMethod method, TD data) in /src/ches/ChesService.cs:line 153\n at Pims.Ches.ChesService.SendEmailAsync(IEmail email) in /src/ches/ChesService.cs:line 239\n at Pims.Notifications.NotificationService.SendAsync(IEmail email) in /src/notifications/NotificationService.cs:line 235\n at Pims.Notifications.NotificationService.SendAsync(NotificationQueue notification) in /src/notifications/NotificationService.cs:line 73\n at Pims.Notifications.NotificationService.SendAsync(NotificationQueue notification) in /src/notifications/NotificationService.cs:line 94\n at Pims.Dal.Services.NotificationQueueService.SendNotificationsAsync(IEnumerable`1 notifications, Boolean saveChanges) in /src/dal/Services/Concrete/NotificationQueueService.cs:line 344\n at Pims.Dal.Services.ProjectService.SendNotificationsAsync(Project project, Nullable`1 fromStatusId, IEnumerable`1 responses, Boolean noteChanged) in /src/dal/Services/Concrete/ProjectService.cs:line 928\n at Pims.Dal.Services.ProjectService.SetStatusAsync(Project project, Workflow workflow, Boolean sendNotifications) in /src/dal/Services/Concrete/ProjectService.cs:line 780\n at Pims.Api.Areas.Project.Controllers.DisposeController.SetStatusAsync(ProjectModel model) in /src/api/Areas/Project/Controllers/DisposeController.cs:line 173\n at Pims.Api.Areas.Project.Controllers.DisposeController.SetStatusAsync(String workflowCode, String statusCode, ProjectModel model) in /src/api/Areas/Project/Controllers/DisposeController.cs:line 198\n at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)\n at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)\n at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n at Pims.Api.Helpers.Middleware.LogRequestMiddleware.Invoke(HttpContext context) in /src/api/Helpers/Middleware/LogRequestMiddleware.cs:line 43\n at Pims.Api.Helpers.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context) in /src/api/Helpers/Middleware/ResponseTimeMiddleware.cs:line 46\n at Pims.Api.Helpers.Middleware.ErrorHandlingMiddleware.Invoke(HttpContext context) in /src/api/Helpers/Middleware/ErrorHandlingMiddleware.cs:line 60"}
```

**Comment by Fosol** [comment]
CHES is moving and a new account needs to be created so that email will continue.

**Review by BradyMitch — APPROVED** [review]

**Comment by BradyMitch** [comment]
> Im getting the following error when clicking Submit at the end of the Create Disposal Project form:
> 
> ```
> /api/projects/dispos: Bad Request data: {"error":"HTTP Request 'https://dev.oidc.gov.bc.ca/auth/realms/jbd6rnxw/protocol/openid-connect/token' failed\n","type":"ChesException","details":"\n\n\n","stackTrace":" at Pims.Ches.ChesService.GetTokenAsync(String username, String password) in /src/ches/ChesService.cs:line 199\n at Pims.Ches.ChesService.RefreshAccessTokenAsync() in /src/ches/ChesService.cs:line 79\n at Pims.Ches.ChesService.SendAsync[TR,TD](String endpoint, HttpMethod method, TD data) in /src/ches/ChesService.cs:line 153\n at Pims.Ches.ChesService.SendEmailAsync(IEmail email) in /src/ches/ChesService.cs:line 239\n at Pims.Notifications.NotificationService.SendAsync(IEmail email) in /src/notifications/NotificationService.cs:line 235\n at Pims.Notifications.NotificationService.SendAsync(NotificationQueue notification) in /src/notifications/NotificationService.cs:line 73\n at Pims.Notifications.NotificationService.SendAsync(NotificationQueue notification) in /src/notifications/NotificationService.cs:line 94\n at Pims.Dal.Services.NotificationQueueService.SendNotificationsAsync(IEnumerable`1 notifications, Boolean saveChanges) in /src/dal/Services/Concrete/NotificationQueueService.cs:line 344\n at Pims.Dal.Services.ProjectService.SendNotificationsAsync(Project project, Nullable`1 fromStatusId, IEnumerable`1 responses, Boolean noteChanged) in /src/dal/Services/Concrete/ProjectService.cs:line 928\n at Pims.Dal.Services.ProjectService.SetStatusAsync(Project project, Workflow workflow, Boolean sendNotifications) in /src/dal/Services/Concrete/ProjectService.cs:line 780\n at Pims.Api.Areas.Project.Controllers.DisposeController.SetStatusAsync(ProjectModel model) in /src/api/Areas/Project/Controllers/DisposeController.cs:line 173\n at Pims.Api.Areas.Project.Controllers.DisposeController.SetStatusAsync(String workflowCode, String statusCode, ProjectModel model) in /src/api/Areas/Project/Controllers/DisposeController.cs:line 198\n at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)\n at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)\n at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n at Pims.Api.Helpers.Middleware.LogRequestMiddleware.Invoke(HttpContext context) in /src/api/Helpers/Middleware/LogRequestMiddleware.cs:line 43\n at Pims.Api.Helpers.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context) in /src/api/Helpers/Middleware/ResponseTimeMiddleware.cs:line 46\n at Pims.Api.Helpers.Middleware.ErrorHandlingMiddleware.Invoke(HttpContext context) in /src/api/Helpers/Middleware/ErrorHandlingMiddleware.cs:line 60"}
> ```

Nevermind, I did a rebuild and now it's working.

**Pull request merged**
