### PR TITLE
PIMS-2107 Email Field Rework

### PR DESCRIPTION
**Pull request by dbarkowsky**
## 🎯 Summary

  
[PIMS-2107](https://citz-imb.atlassian.net/browse/PIMS-2107)

## Changes
- API now verifies emails when submitting an access request or updating a user.
- Email field on the Access Request form is now only prepopulated and locked when it's an IDIR user
- Non-IDIR users can enter emails of their choosing
- Frontend uses Zod to validate the email to stay consistent with the backend.
- User Details editing also has validation added.

## Testing
- Log in with IDIR and BCSC user. See how email field is restricted or not
- Try entering a bad email and submitting
- Try entering a good email and submitting

## 🔰 Checklist

- [x] I have read and agree with the following checklist and am following the guidelines in our [Code of Conduct](CODE_OF_CONDUCT.md) document.

> - I have performed a self-review of my code.
> - I have commented my code, particularly in hard-to-understand areas.
> - I have made corresponding changes to the documentation where required.
> - I have tested my changes to the best of my ability.
> - My changes generate no new warnings.

### CODE REVIEW

**Review by LawrenceLau2020 — COMMENTED** [review]
Tested logging in using one of the test accounts, on first try it actually logged me in bypassing the access request page for some reason, although I didn't see any menu items.

Trying the second time after logging out, then got the access request page. The email address was required and I entered a false email, then when approving the new test user I saw that it stored the test user's actual email address from the BCSC service.

**Comment by TaylorFries** [comment]
interesting thing while testing. I entered my email with the dev bceid account and it seems that it still pulled the email associated with the account to be used. 
Screenshot 2024-09-26 at 8 45 07 AM
Screenshot 2024-09-26 at 8 44 43 AM

**Comment by LawrenceLau2020** [comment]
After this commit: https://github.com/bcgov/PIMS/pull/2701/commits/1da671945d1e6db3360e6653c1398aefab60a498, I'm now able to enter any email address when creating an access request as a BSCS user, and the entered email gets stored properly in the user table.

**Review by TaylorFries — APPROVED** [review]
all changes work as expected.

**Pull request merged**
