### PR TITLE
PIMS-288 Parcel Details Changing Unexpectedly

### PR DESCRIPTION
**Pull request by dbarkowsky**
## 🎯 Summary

  
[PIMS-288: ](https://citz-imb.atlassian.net/browse/PIMS-288?atlOrigin=eyJpIjoiZmViZmU3Yzc0MmY3NDJlZWIxMGU1Yzk1NmM4NWQ5ZDYiLCJwIjoiaiJ9)

## For Buildings
Added a state variable to track if the pin was picked up. The lat and long should only update if that's the case. 

## For Parcels
Shouldn't update unless edit mode is true. Might be a good idea to rework the land select form for parcels to act more like the one for buildings, where you have to pick up the pin in order to change fields with it.

## 🔰 Checklist

- [x] I have read and agree with the following checklist and am following the guidelines in our [Code of Conduct](CODE_OF_CONDUCT.md) document.

> - I have performed a self-review of my code.
> - I have commented my code, particularly in hard-to-understand areas.
> - I have made corresponding changes to the documentation where required.
> - I have tested my changes to the best of my ability.
> - My changes generate no new warnings.

### CODE REVIEW

**Review by LawrenceLau2020 — COMMENTED** [review]
I tried editing an existing property from the "Review" tab, testing a situation where a property maybe located on the wrong parcel/PID, was able to click on the "new" parcel which populated the parcel details form, but there was not "Submit" button to save the changes.

I also tested changing the parcel from the "Step 1 - Parcel ID" tab, clicked on a different parcel, but the PID didn't update:
image

**Comment by dbarkowsky** [comment]
@LawrenceLau2020 I'm not having the same issues. Let's hop on a chat when you have time, so I can see what it's doing for you.

**Review by LawrenceLau2020 — APPROVED** [review]
It seems to be working now, I'm able to select a new parcel and change the PID only from the Parcel ID "step", and I'm not seeing any issues.

**Comment by LawrenceLau2020** [comment]
I tested submitting a new parcel as well as updating an existing parcel, and after clicking on the pin and dropping it on the map, the PID isn't getting populated on the form for some reason:

image

**Pull request merged**
